---
# kubectl taint nodes node1 spray = mortein:NoSchedule
# is how you set a tain on a node
# Different types of taint:
# NoSchedule, PreferNoSchedule, NoExecute

apiVersion: v1
kind: Pod
metadata:
  name: bee
spec:
  containers:
  - name: bee
    image: nginx
  tolerations:
  - key: "spray"
    operator: "Equal"
    value: "mortein"
    effect: "NoSchedule"
